package com.github.jrtb.javarushtelegrambot.javarushclient.dto;

public enum GroupInfoLanguage {
    UNKNOWN, ENGLISH, GERMAN, SPANISH, HINDI,
    FRENCH, PORTUGUESE, POLISH, BENGALI, PUNJABI,
    CHINESE, ITALIAN, INDONESIAN, MARATHI, TAMIL,
    TELUGU, JAPANESE, KOREAN, URDU, TAIWANESE,
    NETHERLANDS, RUSSIAN, UKRAINIAN, BULGARIAN, DANISH,
    HUNGARIAN, JAVANESE, MALAY, NORWEGIAN, ROMANIAN,
    SWEDISH, THAI, FILIPINO, TURKISH, VIETNAMESE
}
